In [6]:
import pandas as pd

df_idx = pd.read_csv('../data/processed/filtered_detailed_results.csv')
df_corpus = pd.read_table('../data/raw/full_lyrics.tsv')

In [14]:
df_idx

,annotator_id,value,sim_rating,id1,id2,pair_id
0,3747424,Apenas existe similitud,2,14251,76075,14251_76075
1,3747424,Completamente diferente,1,29094,33088,29094_33088
2,3747427,Poca similitud,3,37416,59899,37416_59899
3,3747424,Poca similitud,3,31841,3071,31841_3071
4,3747427,Apenas existe similitud,2,37741,35331,37741_35331
...,...,...,...,...,...,...
2023,3748376,Apenas existe similitud,2,48054,19354,48054_19354
2024,3748378,Poca similitud,3,69790,38000,69790_38000
2025,3748394,Similitud Sobresaliente,6,25639,16872,25639_16872
2026,3747469,Poca similitud,3,33088,24450,33088_24450
2027,3748343,Apenas existe similitud,2,14251,10052,14251_10052

In [13]:
df_corpus

,song_id,text,artist_name,track_name
0,5439,"Dulce brillo\nque aún estaba afuera,\ncurtiend...",Eduardo Mateo,Dulce Brillo
1,29094,"No exactamente yo, aunque sí,\npero no lo soy....",Maga,"Sí, Pero No Lo Soy"
2,69790,"Mi novia Ximenita\nle gusta pelear,\npatea de ...",Los Piojos,Ximenita
3,66730,Oh de profundis.\nOh de procella.\nAh Canto.\n...,Arcana,Chant of the Awakening
4,28437,"Hasta la punta de tu luz,\nhasta tu grito más ...",Arbolito,La Máquina
...,...,...,...,...
70,38000,Me gusta cantarle al viento\nporque vuelan mis...,El Halcon De La Sierra,La Feria De Las Flores
71,48594,Y en la plaza de mi pueblo\ndijo el jornalero ...,Reincidentes,Jornaleros Andaluces
72,37194,Me voy a tomar\nese vino que pensás dejar\ny n...,Bulldog,Un Vinito Mas
73,25047,PI PA PU\nPA PA PI PI PA PIUI\nPI PA PI\nPA PI...,Los Visitantes,Pi-Pa-Pu
74,36583,"Romántica incurable, ¿te recuerdas?\nesa noche...",Roberto Calo,Romantica

In [11]:
_df = df_corpus.set_index('song_id')
df = pd.DataFrame()
df['text1']=_df.loc[df_idx.id1].text.reset_index(drop=['song_id'])
df['text2']=_df.loc[df_idx.id2].text.reset_index(drop=['song_id'])
df.reset_index(inplace=True, drop=['index'])
df['id1'] = df_idx.id1
df['id2'] = df_idx.id2
df['labels'] = df_idx.sim_rating.astype(int) - 1

In [12]:
df

,text1,text2,id1,id2,labels
0,"Señora, su hermosura me deslumbra.\nHace mucho...","Empezar un adiós,\nempezar un adiós.\nEsperar ...",14251,76075,1
1,"No exactamente yo, aunque sí,\npero no lo soy....","No cruzaré\ntu lado de la cama,\nquiero entend...",29094,33088,0
2,"Tuve un amor en los campos,\ndulce novia del a...","Ya ha pasado el tiempo,\nya ha pasado el tiemp...",37416,59899,2
3,"Dame del ayer las ansias locas,\ndame del perf...",Vamos a hacer un silencio\nvamos a ver como fu...,31841,3071,2
4,Suenan las campanas del alba\nen la plazuela.\...,"Echen agua en el altar,\npongan agua una vez m...",37741,35331,1
...,...,...,...,...,...
2023,"Canto,\nllanto,\nverso en fin.\nTanto,\nencant...",Larga muchacho tu voz joven\ncomo larga la luz...,48054,19354,1
2024,"Mi novia Ximenita\nle gusta pelear,\npatea de ...",Me gusta cantarle al viento\nporque vuelan mis...,69790,38000,2
2025,Dame otra oportunidad\nnecesito verte una vez ...,Cuando te fuiste tan lejos\nsupe que no ibas a...,25639,16872,5
2026,"No cruzaré\ntu lado de la cama,\nquiero entend...",Volviendo el rostro hacia atrás\nella midió su...,33088,24450,2
2027,"Señora, su hermosura me deslumbra.\nHace mucho...","Adiós, adiós, mi México lindo\nmañana, mañana ...",14251,10052,1

In [15]:
from collections import Counter
print(Counter(df.id1))

Counter({66730: 99, 37485: 69, 28437: 63, 5439: 63, 55093: 60, 29094: 57, 69790: 57, 37461: 57, 35331: 57, 28616: 51, 37416: 48, 48054: 45, 14251: 42, 16987: 42, 3348: 42, 46366: 42, 31841: 39, 62264: 39, 29590: 36, 34119: 36, 22840: 36, 8851: 33, 37844: 33, 30582: 33, 235: 30, 33088: 30, 31722: 30, 36132: 30, 8842: 30, 24369: 30, 26165: 30, 27790: 27, 1868: 27, 32204: 27, 25639: 27, 34125: 24, 3071: 24, 33902: 24, 27446: 24, 16872: 24, 76075: 24, 21227: 24, 37741: 21, 59899: 21, 5088: 21, 15357: 21, 21856: 18, 10052: 18, 10842: 18, 76479: 18, 7291: 18, 24450: 15, 22822: 15, 7727: 15, 72281: 15, 6632: 15, 19354: 12, 52438: 12, 11068: 12, 9975: 12, 12971: 9, 14975: 9, 8719: 9, 11142: 6, 38000: 6, 8863: 6, 69868: 6, 25047: 3, 48594: 3, 12476: 3, 19929: 3, 37194: 3})